package app.mkp.model.client;

import app.mkp.model.common.TandaTerimaFakturAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 13:46:01 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TandaTerimaFakturAMClient extends ApplicationModuleImpl implements TandaTerimaFakturAM {
    /**
     * This is the default constructor (do not remove).
     */
    public TandaTerimaFakturAMClient() {
    }


    public void generateExistingDoc(String dId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"generateExistingDoc",new String [] {"java.lang.String"},new Object[] {dId});
        return;
    }

    public void generateSelfDoc(String dId, String tipeDok) {
        Object _ret =
            this.riInvokeExportedMethod(this,"generateSelfDoc",new String [] {"java.lang.String","java.lang.String"},new Object[] {dId, tipeDok});
        return;
    }

    public void generateAttachDoc(String dId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"generateAttachDoc",new String [] {"java.lang.String"},new Object[] {dId});
        return;
    }
}
