package app.mkp.model.view.menubar;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 19 17:31:35 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppUrlViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppUrlViewImpl() {
    }


    /**
     * Returns the bind variable value for appId.
     * @return bind variable value for appId
     */
    public String getappId() {
        return (String)getNamedWhereClauseParam("appId");
    }

    /**
     * Sets <code>value</code> for bind variable appId.
     * @param value value to bind as appId
     */
    public void setappId(String value) {
        setNamedWhereClauseParam("appId", value);
    }
}
