package app.mkp.model.view.menubar;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 07 10:47:32 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuItemsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MenuItemsViewImpl() {
    }


}
