package app.mkp.model.entity.loa;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 17 11:53:16 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoaMainImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LoaId {
            public Object get(LoaMainImpl obj) {
                return obj.getLoaId();
            }

            public void put(LoaMainImpl obj, Object value) {
                obj.setLoaId((DBSequence)value);
            }
        }
        ,
        LoaTipe {
            public Object get(LoaMainImpl obj) {
                return obj.getLoaTipe();
            }

            public void put(LoaMainImpl obj, Object value) {
                obj.setLoaTipe((String)value);
            }
        }
        ,
        Descr {
            public Object get(LoaMainImpl obj) {
                return obj.getDescr();
            }

            public void put(LoaMainImpl obj, Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        LoaAuth {
            public Object get(LoaMainImpl obj) {
                return obj.getLoaAuth();
            }

            public void put(LoaMainImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LoaMainImpl object);

        public abstract void put(LoaMainImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int LOAID = AttributesEnum.LoaId.index();
    public static final int LOATIPE = AttributesEnum.LoaTipe.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int LOAAUTH = AttributesEnum.LoaAuth.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoaMainImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("app.mkp.model.entity.loa.LoaMain");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for LoaId, using the alias name LoaId.
     * @return the LoaId
     */
    public DBSequence getLoaId() {
        return (DBSequence)getAttributeInternal(LOAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoaId.
     * @param value value to set the LoaId
     */
    public void setLoaId(DBSequence value) {
        setAttributeInternal(LOAID, value);
    }

    /**
     * Gets the attribute value for LoaTipe, using the alias name LoaTipe.
     * @return the LoaTipe
     */
    public String getLoaTipe() {
        return (String)getAttributeInternal(LOATIPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoaTipe.
     * @param value value to set the LoaTipe
     */
    public void setLoaTipe(String value) {
        setAttributeInternal(LOATIPE, value);
    }

    /**
     * Gets the attribute value for Descr, using the alias name Descr.
     * @return the Descr
     */
    public String getDescr() {
        return (String)getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Descr.
     * @param value value to set the Descr
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLoaAuth() {
        return (RowIterator)getAttributeInternal(LOAAUTH);
    }


    /**
     * @param loaId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence loaId) {
        return new Key(new Object[]{loaId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
             super.create(attributeList);
             SequenceImpl seq = new SequenceImpl("LOA_MAIN_SEQ", getDBTransaction());
             this.setLoaId(new DBSequence(seq.getSequenceNumber()));
     }
}
