package app.mkp.model.view.ttf.createnew;

import app.mkp.model.entity.ttf.MknTtfImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 14:12:48 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknTtfViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Did {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getDid();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setDid((Number)value);
            }
        }
        ,
        IdDokumen {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getIdDokumen();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setIdDokumen((String)value);
            }
        }
        ,
        Id {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getId();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setId((String)value);
            }
        }
        ,
        Status {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setStatus((Integer)value);
            }
        }
        ,
        UnitcompanyId {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getUnitcompanyId();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setUnitcompanyId((String)value);
            }
        }
        ,
        DepartmentId {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getDepartmentId();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setDepartmentId((String)value);
            }
        }
        ,
        GroupTtf {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getGroupTtf();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setGroupTtf((String)value);
            }
        }
        ,
        Trndate {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getTrndate();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setTrndate((Date)value);
            }
        }
        ,
        Trncode {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getTrncode();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setTrncode((String)value);
            }
        }
        ,
        Refno {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getRefno();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setRefno((String)value);
            }
        }
        ,
        Period {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getPeriod();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setPeriod((String)value);
            }
        }
        ,
        SupplierId {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getSupplierId();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setSupplierId((String)value);
            }
        }
        ,
        PoNo {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getPoNo();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setPoNo((String)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        InvoiceDate {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getInvoiceDate();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setInvoiceDate((Date)value);
            }
        }
        ,
        InvoiceDuedate {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getInvoiceDuedate();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setInvoiceDuedate((Date)value);
            }
        }
        ,
        Duedate {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getDuedate();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setDuedate((Date)value);
            }
        }
        ,
        Descr {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getDescr();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        CurrencyId {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getCurrencyId();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setCurrencyId((String)value);
            }
        }
        ,
        Amount {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getAmount();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        Memotext {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getMemotext();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setMemotext((String)value);
            }
        }
        ,
        CreateBy {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getCreateBy();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setCreateBy((String)value);
            }
        }
        ,
        CreateDate {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        TglTerimaDok {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getTglTerimaDok();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setTglTerimaDok((Date)value);
            }
        }
        ,
        CostCenter {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getCostCenter();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setCostCenter((String)value);
            }
        }
        ,
        PembayaranKe {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getPembayaranKe();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setPembayaranKe((Integer)value);
            }
        }
        ,
        KontrakNo {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getKontrakNo();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setKontrakNo((String)value);
            }
        }
        ,
        ImNo {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getImNo();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setImNo((String)value);
            }
        }
        ,
        TipePembelian {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getTipePembelian();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setTipePembelian((String)value);
            }
        }
        ,
        Id1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getId1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setId1((String)value);
            }
        }
        ,
        Id2 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getId2();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setId2((String)value);
            }
        }
        ,
        Id3 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getId3();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setId3((String)value);
            }
        }
        ,
        NoTtf {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getNoTtf();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setNoTtf((String)value);
            }
        }
        ,
        BuktiBayarNum {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getBuktiBayarNum();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setBuktiBayarNum((Long)value);
            }
        }
        ,
        CreateDt {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getCreateDt();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setCreateDt((Date)value);
            }
        }
        ,
        MknTtfReqDocView {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getMknTtfReqDocView();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MknTtfAddedDocView {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getMknTtfAddedDocView();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovUnitCompany1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovUnitCompany1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovCurrency1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovCurrency1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovPembayaranKe1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovPembayaranKe1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovDepartment1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovDepartment1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovSupplierVendor1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovSupplierVendor1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovTipePembelian1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovTipePembelian1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovKodeBeban1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovKodeBeban1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovStatus1 {
            public Object get(MknTtfViewRowImpl obj) {
                return obj.getLovStatus1();
            }

            public void put(MknTtfViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MknTtfViewRowImpl object);

        public abstract void put(MknTtfViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DID = AttributesEnum.Did.index();
    public static final int IDDOKUMEN = AttributesEnum.IdDokumen.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int UNITCOMPANYID = AttributesEnum.UnitcompanyId.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int GROUPTTF = AttributesEnum.GroupTtf.index();
    public static final int TRNDATE = AttributesEnum.Trndate.index();
    public static final int TRNCODE = AttributesEnum.Trncode.index();
    public static final int REFNO = AttributesEnum.Refno.index();
    public static final int PERIOD = AttributesEnum.Period.index();
    public static final int SUPPLIERID = AttributesEnum.SupplierId.index();
    public static final int PONO = AttributesEnum.PoNo.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int INVOICEDUEDATE = AttributesEnum.InvoiceDuedate.index();
    public static final int DUEDATE = AttributesEnum.Duedate.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int CURRENCYID = AttributesEnum.CurrencyId.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int MEMOTEXT = AttributesEnum.Memotext.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int TGLTERIMADOK = AttributesEnum.TglTerimaDok.index();
    public static final int COSTCENTER = AttributesEnum.CostCenter.index();
    public static final int PEMBAYARANKE = AttributesEnum.PembayaranKe.index();
    public static final int KONTRAKNO = AttributesEnum.KontrakNo.index();
    public static final int IMNO = AttributesEnum.ImNo.index();
    public static final int TIPEPEMBELIAN = AttributesEnum.TipePembelian.index();
    public static final int ID1 = AttributesEnum.Id1.index();
    public static final int ID2 = AttributesEnum.Id2.index();
    public static final int ID3 = AttributesEnum.Id3.index();
    public static final int NOTTF = AttributesEnum.NoTtf.index();
    public static final int BUKTIBAYARNUM = AttributesEnum.BuktiBayarNum.index();
    public static final int CREATEDT = AttributesEnum.CreateDt.index();
    public static final int MKNTTFREQDOCVIEW = AttributesEnum.MknTtfReqDocView.index();
    public static final int MKNTTFADDEDDOCVIEW = AttributesEnum.MknTtfAddedDocView.index();
    public static final int LOVUNITCOMPANY1 = AttributesEnum.LovUnitCompany1.index();
    public static final int LOVCURRENCY1 = AttributesEnum.LovCurrency1.index();
    public static final int LOVPEMBAYARANKE1 = AttributesEnum.LovPembayaranKe1.index();
    public static final int LOVDEPARTMENT1 = AttributesEnum.LovDepartment1.index();
    public static final int LOVSUPPLIERVENDOR1 = AttributesEnum.LovSupplierVendor1.index();
    public static final int LOVTIPEPEMBELIAN1 = AttributesEnum.LovTipePembelian1.index();
    public static final int LOVKODEBEBAN1 = AttributesEnum.LovKodeBeban1.index();
    public static final int LOVSTATUS1 = AttributesEnum.LovStatus1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MknTtfViewRowImpl() {
    }

    /**
     * Gets MknTtf entity object.
     * @return the MknTtf
     */
    public MknTtfImpl getMknTtf() {
        return (MknTtfImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DID using the alias name Did.
     * @return the DID
     */
    public Number getDid() {
        return (Number) getAttributeInternal(DID);
    }

    /**
     * Sets <code>value</code> as attribute value for DID using the alias name Did.
     * @param value value to set the DID
     */
    public void setDid(Number value) {
        setAttributeInternal(DID, value);
    }

    /**
     * Gets the attribute value for ID_DOKUMEN using the alias name IdDokumen.
     * @return the ID_DOKUMEN
     */
    public String getIdDokumen() {
        return (String) getAttributeInternal(IDDOKUMEN);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_DOKUMEN using the alias name IdDokumen.
     * @param value value to set the ID_DOKUMEN
     */
    public void setIdDokumen(String value) {
        setAttributeInternal(IDDOKUMEN, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public Integer getStatus() {
        return (Integer) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(Integer value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for UNITCOMPANY_ID using the alias name UnitcompanyId.
     * @return the UNITCOMPANY_ID
     */
    public String getUnitcompanyId() {
        return (String) getAttributeInternal(UNITCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for UNITCOMPANY_ID using the alias name UnitcompanyId.
     * @param value value to set the UNITCOMPANY_ID
     */
    public void setUnitcompanyId(String value) {
        setAttributeInternal(UNITCOMPANYID, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public String getDepartmentId() {
        return (String) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(String value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for GROUP_TTF using the alias name GroupTtf.
     * @return the GROUP_TTF
     */
    public String getGroupTtf() {
        return (String) getAttributeInternal(GROUPTTF);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_TTF using the alias name GroupTtf.
     * @param value value to set the GROUP_TTF
     */
    public void setGroupTtf(String value) {
        setAttributeInternal(GROUPTTF, value);
    }

    /**
     * Gets the attribute value for TRNDATE using the alias name Trndate.
     * @return the TRNDATE
     */
    public Date getTrndate() {
        return (Date) getAttributeInternal(TRNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRNDATE using the alias name Trndate.
     * @param value value to set the TRNDATE
     */
    public void setTrndate(Date value) {
        setAttributeInternal(TRNDATE, value);
    }

    /**
     * Gets the attribute value for TRNCODE using the alias name Trncode.
     * @return the TRNCODE
     */
    public String getTrncode() {
        return (String) getAttributeInternal(TRNCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRNCODE using the alias name Trncode.
     * @param value value to set the TRNCODE
     */
    public void setTrncode(String value) {
        setAttributeInternal(TRNCODE, value);
    }

    /**
     * Gets the attribute value for REFNO using the alias name Refno.
     * @return the REFNO
     */
    public String getRefno() {
        return (String) getAttributeInternal(REFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REFNO using the alias name Refno.
     * @param value value to set the REFNO
     */
    public void setRefno(String value) {
        setAttributeInternal(REFNO, value);
    }

    /**
     * Gets the attribute value for PERIOD using the alias name Period.
     * @return the PERIOD
     */
    public String getPeriod() {
        return (String) getAttributeInternal(PERIOD);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD using the alias name Period.
     * @param value value to set the PERIOD
     */
    public void setPeriod(String value) {
        setAttributeInternal(PERIOD, value);
    }

    /**
     * Gets the attribute value for SUPPLIER_ID using the alias name SupplierId.
     * @return the SUPPLIER_ID
     */
    public String getSupplierId() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIER_ID using the alias name SupplierId.
     * @param value value to set the SUPPLIER_ID
     */
    public void setSupplierId(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for PO_NO using the alias name PoNo.
     * @return the PO_NO
     */
    public String getPoNo() {
        return (String) getAttributeInternal(PONO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_NO using the alias name PoNo.
     * @param value value to set the PO_NO
     */
    public void setPoNo(String value) {
        setAttributeInternal(PONO, value);
    }

    /**
     * Gets the attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @return the INVOICE_NO
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @param value value to set the INVOICE_NO
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @return the INVOICE_DATE
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @param value value to set the INVOICE_DATE
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for INVOICE_DUEDATE using the alias name InvoiceDuedate.
     * @return the INVOICE_DUEDATE
     */
    public Date getInvoiceDuedate() {
        return (Date) getAttributeInternal(INVOICEDUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_DUEDATE using the alias name InvoiceDuedate.
     * @param value value to set the INVOICE_DUEDATE
     */
    public void setInvoiceDuedate(Date value) {
        setAttributeInternal(INVOICEDUEDATE, value);
    }

    /**
     * Gets the attribute value for DUEDATE using the alias name Duedate.
     * @return the DUEDATE
     */
    public Date getDuedate() {
        return (Date) getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUEDATE using the alias name Duedate.
     * @param value value to set the DUEDATE
     */
    public void setDuedate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for DESCR using the alias name Descr.
     * @return the DESCR
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCR using the alias name Descr.
     * @param value value to set the DESCR
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * Gets the attribute value for CURRENCY_ID using the alias name CurrencyId.
     * @return the CURRENCY_ID
     */
    public String getCurrencyId() {
        return (String) getAttributeInternal(CURRENCYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_ID using the alias name CurrencyId.
     * @param value value to set the CURRENCY_ID
     */
    public void setCurrencyId(String value) {
        setAttributeInternal(CURRENCYID, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for MEMOTEXT using the alias name Memotext.
     * @return the MEMOTEXT
     */
    public String getMemotext() {
        return (String) getAttributeInternal(MEMOTEXT);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMOTEXT using the alias name Memotext.
     * @param value value to set the MEMOTEXT
     */
    public void setMemotext(String value) {
        setAttributeInternal(MEMOTEXT, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_BY using the alias name CreateBy.
     * @param value value to set the CREATE_BY
     */
    public void setCreateBy(String value) {
        setAttributeInternal(CREATEBY, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for TGL_TERIMA_DOK using the alias name TglTerimaDok.
     * @return the TGL_TERIMA_DOK
     */
    public Date getTglTerimaDok() {
        return (Date) getAttributeInternal(TGLTERIMADOK);
    }

    /**
     * Sets <code>value</code> as attribute value for TGL_TERIMA_DOK using the alias name TglTerimaDok.
     * @param value value to set the TGL_TERIMA_DOK
     */
    public void setTglTerimaDok(Date value) {
        setAttributeInternal(TGLTERIMADOK, value);
    }

    /**
     * Gets the attribute value for COST_CENTER using the alias name CostCenter.
     * @return the COST_CENTER
     */
    public String getCostCenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CENTER using the alias name CostCenter.
     * @param value value to set the COST_CENTER
     */
    public void setCostCenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for PEMBAYARAN_KE using the alias name PembayaranKe.
     * @return the PEMBAYARAN_KE
     */
    public Integer getPembayaranKe() {
        return (Integer) getAttributeInternal(PEMBAYARANKE);
    }

    /**
     * Sets <code>value</code> as attribute value for PEMBAYARAN_KE using the alias name PembayaranKe.
     * @param value value to set the PEMBAYARAN_KE
     */
    public void setPembayaranKe(Integer value) {
        setAttributeInternal(PEMBAYARANKE, value);
    }

    /**
     * Gets the attribute value for KONTRAK_NO using the alias name KontrakNo.
     * @return the KONTRAK_NO
     */
    public String getKontrakNo() {
        return (String) getAttributeInternal(KONTRAKNO);
    }

    /**
     * Sets <code>value</code> as attribute value for KONTRAK_NO using the alias name KontrakNo.
     * @param value value to set the KONTRAK_NO
     */
    public void setKontrakNo(String value) {
        setAttributeInternal(KONTRAKNO, value);
    }

    /**
     * Gets the attribute value for IM_NO using the alias name ImNo.
     * @return the IM_NO
     */
    public String getImNo() {
        return (String) getAttributeInternal(IMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_NO using the alias name ImNo.
     * @param value value to set the IM_NO
     */
    public void setImNo(String value) {
        setAttributeInternal(IMNO, value);
    }

    /**
     * Gets the attribute value for TIPE_PEMBELIAN using the alias name TipePembelian.
     * @return the TIPE_PEMBELIAN
     */
    public String getTipePembelian() {
        return (String) getAttributeInternal(TIPEPEMBELIAN);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPE_PEMBELIAN using the alias name TipePembelian.
     * @param value value to set the TIPE_PEMBELIAN
     */
    public void setTipePembelian(String value) {
        setAttributeInternal(TIPEPEMBELIAN, value);
    }

    /**
     * Gets the attribute value for ID1 using the alias name Id1.
     * @return the ID1
     */
    public String getId1() {
        return (String) getAttributeInternal(ID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ID1 using the alias name Id1.
     * @param value value to set the ID1
     */
    public void setId1(String value) {
        setAttributeInternal(ID1, value);
    }

    /**
     * Gets the attribute value for ID2 using the alias name Id2.
     * @return the ID2
     */
    public String getId2() {
        return (String) getAttributeInternal(ID2);
    }

    /**
     * Sets <code>value</code> as attribute value for ID2 using the alias name Id2.
     * @param value value to set the ID2
     */
    public void setId2(String value) {
        setAttributeInternal(ID2, value);
    }

    /**
     * Gets the attribute value for ID3 using the alias name Id3.
     * @return the ID3
     */
    public String getId3() {
        return (String) getAttributeInternal(ID3);
    }

    /**
     * Sets <code>value</code> as attribute value for ID3 using the alias name Id3.
     * @param value value to set the ID3
     */
    public void setId3(String value) {
        setAttributeInternal(ID3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoTtf.
     * @return the NoTtf
     */
    public String getNoTtf() {
        return (String) getAttributeInternal(NOTTF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoTtf.
     * @param value value to set the  NoTtf
     */
    public void setNoTtf(String value) {
        setAttributeInternal(NOTTF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuktiBayarNum.
     * @return the BuktiBayarNum
     */
    public Long getBuktiBayarNum() {
        return (Long) getAttributeInternal(BUKTIBAYARNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuktiBayarNum.
     * @param value value to set the  BuktiBayarNum
     */
    public void setBuktiBayarNum(Long value) {
        setAttributeInternal(BUKTIBAYARNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateDt.
     * @return the CreateDt
     */
    public Date getCreateDt() {
        return (Date) getAttributeInternal(CREATEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreateDt.
     * @param value value to set the  CreateDt
     */
    public void setCreateDt(Date value) {
        setAttributeInternal(CREATEDT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MknTtfReqDocView.
     */
    public RowIterator getMknTtfReqDocView() {
        return (RowIterator)getAttributeInternal(MKNTTFREQDOCVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MknTtfAddedDocView.
     */
    public RowIterator getMknTtfAddedDocView() {
        return (RowIterator)getAttributeInternal(MKNTTFADDEDDOCVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovUnitCompany1.
     */
    public RowSet getLovUnitCompany1() {
        return (RowSet)getAttributeInternal(LOVUNITCOMPANY1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovCurrency1.
     */
    public RowSet getLovCurrency1() {
        return (RowSet)getAttributeInternal(LOVCURRENCY1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovPembayaranKe1.
     */
    public RowSet getLovPembayaranKe1() {
        return (RowSet)getAttributeInternal(LOVPEMBAYARANKE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovDepartment1.
     */
    public RowSet getLovDepartment1() {
        return (RowSet)getAttributeInternal(LOVDEPARTMENT1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovSupplierVendor1.
     */
    public RowSet getLovSupplierVendor1() {
        return (RowSet)getAttributeInternal(LOVSUPPLIERVENDOR1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovTipePembelian1.
     */
    public RowSet getLovTipePembelian1() {
        return (RowSet)getAttributeInternal(LOVTIPEPEMBELIAN1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovKodeBeban1.
     */
    public RowSet getLovKodeBeban1() {
        return (RowSet)getAttributeInternal(LOVKODEBEBAN1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovStatus1.
     */
    public RowSet getLovStatus1() {
        return (RowSet)getAttributeInternal(LOVSTATUS1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
