package app.mkp.model.view.ttf.createnew;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 14:06:00 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknTtfAddedDocViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TtfNo {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getTtfNo();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setTtfNo((String)value);
            }
        }
        ,
        Did {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getDid();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setDid((Number)value);
            }
        }
        ,
        AppId {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getAppId();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setAppId((String)value);
            }
        }
        ,
        AppUrl1 {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getAppUrl1();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setAppUrl1((String)value);
            }
        }
        ,
        DocTitle {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getDocTitle();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setDocTitle((String)value);
            }
        }
        ,
        DocName {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getDocName();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setDocName((String)value);
            }
        }
        ,
        Did1 {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getDid1();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setDid1((Number)value);
            }
        }
        ,
        Url {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getUrl();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setUrl((String)value);
            }
        }
        ,
        MetaUrl {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getMetaUrl();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setMetaUrl((String)value);
            }
        }
        ,
        TipeDokumen {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getTipeDokumen();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setTipeDokumen((String)value);
            }
        }
        ,
        LovDmsMeta1 {
            public Object get(MknTtfAddedDocViewRowImpl obj) {
                return obj.getLovDmsMeta1();
            }

            public void put(MknTtfAddedDocViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MknTtfAddedDocViewRowImpl object);

        public abstract void put(MknTtfAddedDocViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TTFNO = AttributesEnum.TtfNo.index();
    public static final int DID = AttributesEnum.Did.index();
    public static final int APPID = AttributesEnum.AppId.index();
    public static final int APPURL1 = AttributesEnum.AppUrl1.index();
    public static final int DOCTITLE = AttributesEnum.DocTitle.index();
    public static final int DOCNAME = AttributesEnum.DocName.index();
    public static final int DID1 = AttributesEnum.Did1.index();
    public static final int URL = AttributesEnum.Url.index();
    public static final int METAURL = AttributesEnum.MetaUrl.index();
    public static final int TIPEDOKUMEN = AttributesEnum.TipeDokumen.index();
    public static final int LOVDMSMETA1 = AttributesEnum.LovDmsMeta1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MknTtfAddedDocViewRowImpl() {
    }

    /**
     * Gets MknTtfAddedDoc entity object.
     * @return the MknTtfAddedDoc
     */
    public EntityImpl getMknTtfAddedDoc() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets AppUrl entity object.
     * @return the AppUrl
     */
    public EntityImpl getAppUrl() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets MknDmsMeta entity object.
     * @return the MknDmsMeta
     */
    public EntityImpl getMknDmsMeta() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for TTF_NO using the alias name TtfNo.
     * @return the TTF_NO
     */
    public String getTtfNo() {
        return (String) getAttributeInternal(TTFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TTF_NO using the alias name TtfNo.
     * @param value value to set the TTF_NO
     */
    public void setTtfNo(String value) {
        setAttributeInternal(TTFNO, value);
    }

    /**
     * Gets the attribute value for DID using the alias name Did.
     * @return the DID
     */
    public Number getDid() {
        return (Number) getAttributeInternal(DID);
    }

    /**
     * Sets <code>value</code> as attribute value for DID using the alias name Did.
     * @param value value to set the DID
     */
    public void setDid(Number value) {
        setAttributeInternal(DID, value);
    }

    /**
     * Gets the attribute value for APP_ID using the alias name AppId.
     * @return the APP_ID
     */
    public String getAppId() {
        return (String) getAttributeInternal(APPID);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_ID using the alias name AppId.
     * @param value value to set the APP_ID
     */
    public void setAppId(String value) {
        setAttributeInternal(APPID, value);
    }

    /**
     * Gets the attribute value for APP_URL using the alias name AppUrl1.
     * @return the APP_URL
     */
    public String getAppUrl1() {
        return (String) getAttributeInternal(APPURL1);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_URL using the alias name AppUrl1.
     * @param value value to set the APP_URL
     */
    public void setAppUrl1(String value) {
        setAttributeInternal(APPURL1, value);
    }

    /**
     * Gets the attribute value for DOC_TITLE using the alias name DocTitle.
     * @return the DOC_TITLE
     */
    public String getDocTitle() {
        return (String) getAttributeInternal(DOCTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TITLE using the alias name DocTitle.
     * @param value value to set the DOC_TITLE
     */
    public void setDocTitle(String value) {
        setAttributeInternal(DOCTITLE, value);
    }

    /**
     * Gets the attribute value for DOC_NAME using the alias name DocName.
     * @return the DOC_NAME
     */
    public String getDocName() {
        return (String) getAttributeInternal(DOCNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_NAME using the alias name DocName.
     * @param value value to set the DOC_NAME
     */
    public void setDocName(String value) {
        setAttributeInternal(DOCNAME, value);
    }

    /**
     * Gets the attribute value for DID using the alias name Did1.
     * @return the DID
     */
    public Number getDid1() {
        return (Number) getAttributeInternal(DID1);
    }

    /**
     * Sets <code>value</code> as attribute value for DID using the alias name Did1.
     * @param value value to set the DID
     */
    public void setDid1(Number value) {
        setAttributeInternal(DID1, value);
    }

    /**
     * Gets the attribute value for URL using the alias name Url.
     * @return the URL
     */
    public String getUrl() {
        return (String) getAttributeInternal(URL);
    }

    /**
     * Sets <code>value</code> as attribute value for URL using the alias name Url.
     * @param value value to set the URL
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MetaUrl.
     * @return the MetaUrl
     */
    public String getMetaUrl() {
        return (String) getAttributeInternal(METAURL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MetaUrl.
     * @param value value to set the  MetaUrl
     */
    public void setMetaUrl(String value) {
        setAttributeInternal(METAURL, value);
    }

    /**
     * Gets the attribute value for TIPE_DOKUMEN using the alias name TipeDokumen.
     * @return the TIPE_DOKUMEN
     */
    public String getTipeDokumen() {
        return (String) getAttributeInternal(TIPEDOKUMEN);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPE_DOKUMEN using the alias name TipeDokumen.
     * @param value value to set the TIPE_DOKUMEN
     */
    public void setTipeDokumen(String value) {
        setAttributeInternal(TIPEDOKUMEN, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovDmsMeta1.
     */
    public RowSet getLovDmsMeta1() {
        return (RowSet)getAttributeInternal(LOVDMSMETA1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
