package app.mkp.model.view.ttf.createnew;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 13:39:37 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknTtfExistingDocViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MknTtfExistingDocViewImpl() {
    }

    /**
     * Returns the bind variable value for invDid.
     * @return bind variable value for invDid
     */
    public String getinvDid() {
        return (String)getNamedWhereClauseParam("invDid");
    }

    /**
     * Sets <code>value</code> for bind variable invDid.
     * @param value value to bind as invDid
     */
    public void setinvDid(String value) {
        setNamedWhereClauseParam("invDid", value);
    }
}
