package app.mkp.model.view.ttf.createnew;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 09:22:39 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknTtfKontrakPlafonValidationRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        NilaiKontrak {
            public Object get(MknTtfKontrakPlafonValidationRowImpl obj) {
                return obj.getNilaiKontrak();
            }

            public void put(MknTtfKontrakPlafonValidationRowImpl obj,
                            Object value) {
                obj.setNilaiKontrak((Number)value);
            }
        }
        ,
        SumNilInv {
            public Object get(MknTtfKontrakPlafonValidationRowImpl obj) {
                return obj.getSumNilInv();
            }

            public void put(MknTtfKontrakPlafonValidationRowImpl obj,
                            Object value) {
                obj.setSumNilInv((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MknTtfKontrakPlafonValidationRowImpl object);

        public abstract void put(MknTtfKontrakPlafonValidationRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int NILAIKONTRAK = AttributesEnum.NilaiKontrak.index();
    public static final int SUMNILINV = AttributesEnum.SumNilInv.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MknTtfKontrakPlafonValidationRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute NilaiKontrak.
     * @return the NilaiKontrak
     */
    public Number getNilaiKontrak() {
        return (Number) getAttributeInternal(NILAIKONTRAK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NilaiKontrak.
     * @param value value to set the  NilaiKontrak
     */
    public void setNilaiKontrak(Number value) {
        setAttributeInternal(NILAIKONTRAK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumNilInv.
     * @return the SumNilInv
     */
    public Number getSumNilInv() {
        return (Number) getAttributeInternal(SUMNILINV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumNilInv.
     * @param value value to set the  SumNilInv
     */
    public void setSumNilInv(Number value) {
        setAttributeInternal(SUMNILINV, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
