package app.mkp.model.view.ttf.createnew;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 14:12:48 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknTtfViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MknTtfViewImpl() {
    }
}
