package app.mkp.model.view.ttf.createnew;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 17 08:26:45 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknTtfValidationViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MknTtfValidationViewImpl() {
    }

    /**
     * Returns the bind variable value for invNo.
     * @return bind variable value for invNo
     */
    public String getinvNo() {
        return (String)getNamedWhereClauseParam("invNo");
    }

    /**
     * Sets <code>value</code> for bind variable invNo.
     * @param value value to bind as invNo
     */
    public void setinvNo(String value) {
        setNamedWhereClauseParam("invNo", value);
    }


}
