package app.mkp.model.view.menubar;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 19 17:31:34 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppUrlViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AppId {
            public Object get(AppUrlViewRowImpl obj) {
                return obj.getAppId();
            }

            public void put(AppUrlViewRowImpl obj, Object value) {
                obj.setAppId((String)value);
            }
        }
        ,
        AppUrl1 {
            public Object get(AppUrlViewRowImpl obj) {
                return obj.getAppUrl1();
            }

            public void put(AppUrlViewRowImpl obj, Object value) {
                obj.setAppUrl1((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(AppUrlViewRowImpl object);

        public abstract void put(AppUrlViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPID = AttributesEnum.AppId.index();
    public static final int APPURL1 = AttributesEnum.AppUrl1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AppUrlViewRowImpl() {
    }

    /**
     * Gets AppUrl entity object.
     * @return the AppUrl
     */
    public EntityImpl getAppUrl() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for APP_ID using the alias name AppId.
     * @return the APP_ID
     */
    public String getAppId() {
        return (String) getAttributeInternal(APPID);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_ID using the alias name AppId.
     * @param value value to set the APP_ID
     */
    public void setAppId(String value) {
        setAttributeInternal(APPID, value);
    }

    /**
     * Gets the attribute value for APP_URL using the alias name AppUrl1.
     * @return the APP_URL
     */
    public String getAppUrl1() {
        return (String) getAttributeInternal(APPURL1);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_URL using the alias name AppUrl1.
     * @param value value to set the APP_URL
     */
    public void setAppUrl1(String value) {
        setAttributeInternal(APPURL1, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
