package app.mkp.model.view.ttf.linkdoc;

import app.mkp.model.entity.ttf.linkdoc.MknDokLinkImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 19 14:13:49 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknDokLinkViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getId();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setId((DBSequence)value);
            }
        }
        ,
        LinkDokDid {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getLinkDokDid();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setLinkDokDid((Integer)value);
            }
        }
        ,
        Did {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getDid();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setDid((Integer)value);
            }
        }
        ,
        NoParent {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getNoParent();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setNoParent((String)value);
            }
        }
        ,
        TipeDok {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getTipeDok();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setTipeDok((String)value);
            }
        }
        ,
        AppUrl1 {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getAppUrl1();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setAppUrl1((String)value);
            }
        }
        ,
        AppId {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getAppId();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setAppId((String)value);
            }
        }
        ,
        DocTitle {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getDocTitle();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setDocTitle((String)value);
            }
        }
        ,
        DocName {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getDocName();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setDocName((String)value);
            }
        }
        ,
        Did1 {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getDid1();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setDid1((Number)value);
            }
        }
        ,
        Url {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getUrl();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setUrl((String)value);
            }
        }
        ,
        TipeDokumen {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getTipeDokumen();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setTipeDokumen((String)value);
            }
        }
        ,
        MetaUrl {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getMetaUrl();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setMetaUrl((String)value);
            }
        }
        ,
        LovDmsMeta1 {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getLovDmsMeta1();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovYesNo1 {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getLovYesNo1();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovTipeDokumen1 {
            public Object get(MknDokLinkViewRowImpl obj) {
                return obj.getLovTipeDokumen1();
            }

            public void put(MknDokLinkViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MknDokLinkViewRowImpl object);

        public abstract void put(MknDokLinkViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int LINKDOKDID = AttributesEnum.LinkDokDid.index();
    public static final int DID = AttributesEnum.Did.index();
    public static final int NOPARENT = AttributesEnum.NoParent.index();
    public static final int TIPEDOK = AttributesEnum.TipeDok.index();
    public static final int APPURL1 = AttributesEnum.AppUrl1.index();
    public static final int APPID = AttributesEnum.AppId.index();
    public static final int DOCTITLE = AttributesEnum.DocTitle.index();
    public static final int DOCNAME = AttributesEnum.DocName.index();
    public static final int DID1 = AttributesEnum.Did1.index();
    public static final int URL = AttributesEnum.Url.index();
    public static final int TIPEDOKUMEN = AttributesEnum.TipeDokumen.index();
    public static final int METAURL = AttributesEnum.MetaUrl.index();
    public static final int LOVDMSMETA1 = AttributesEnum.LovDmsMeta1.index();
    public static final int LOVYESNO1 = AttributesEnum.LovYesNo1.index();
    public static final int LOVTIPEDOKUMEN1 = AttributesEnum.LovTipeDokumen1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MknDokLinkViewRowImpl() {
    }

    /**
     * Gets MknDokLink entity object.
     * @return the MknDokLink
     */
    public MknDokLinkImpl getMknDokLink() {
        return (MknDokLinkImpl)getEntity(0);
    }

    /**
     * Gets MknDmsMeta entity object.
     * @return the MknDmsMeta
     */
    public EntityImpl getMknDmsMeta() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets AppUrl entity object.
     * @return the AppUrl
     */
    public EntityImpl getAppUrl() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for LINK_DOK_DID using the alias name LinkDokDid.
     * @return the LINK_DOK_DID
     */
    public Integer getLinkDokDid() {
        return (Integer) getAttributeInternal(LINKDOKDID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINK_DOK_DID using the alias name LinkDokDid.
     * @param value value to set the LINK_DOK_DID
     */
    public void setLinkDokDid(Integer value) {
        setAttributeInternal(LINKDOKDID, value);
    }

    /**
     * Gets the attribute value for DID using the alias name Did.
     * @return the DID
     */
    public Integer getDid() {
        return (Integer) getAttributeInternal(DID);
    }

    /**
     * Sets <code>value</code> as attribute value for DID using the alias name Did.
     * @param value value to set the DID
     */
    public void setDid(Integer value) {
        setAttributeInternal(DID, value);
    }

    /**
     * Gets the attribute value for NO_PARENT using the alias name NoParent.
     * @return the NO_PARENT
     */
    public String getNoParent() {
        return (String) getAttributeInternal(NOPARENT);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_PARENT using the alias name NoParent.
     * @param value value to set the NO_PARENT
     */
    public void setNoParent(String value) {
        setAttributeInternal(NOPARENT, value);
    }

    /**
     * Gets the attribute value for TIPE_DOK using the alias name TipeDok.
     * @return the TIPE_DOK
     */
    public String getTipeDok() {
        return (String) getAttributeInternal(TIPEDOK);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPE_DOK using the alias name TipeDok.
     * @param value value to set the TIPE_DOK
     */
    public void setTipeDok(String value) {
        setAttributeInternal(TIPEDOK, value);
    }

    /**
     * Gets the attribute value for APP_URL using the alias name AppUrl1.
     * @return the APP_URL
     */
    public String getAppUrl1() {
        return (String) getAttributeInternal(APPURL1);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_URL using the alias name AppUrl1.
     * @param value value to set the APP_URL
     */
    public void setAppUrl1(String value) {
        setAttributeInternal(APPURL1, value);
    }

    /**
     * Gets the attribute value for APP_ID using the alias name AppId.
     * @return the APP_ID
     */
    public String getAppId() {
        return (String) getAttributeInternal(APPID);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_ID using the alias name AppId.
     * @param value value to set the APP_ID
     */
    public void setAppId(String value) {
        setAttributeInternal(APPID, value);
    }

    /**
     * Gets the attribute value for DOC_TITLE using the alias name DocTitle.
     * @return the DOC_TITLE
     */
    public String getDocTitle() {
        return (String) getAttributeInternal(DOCTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TITLE using the alias name DocTitle.
     * @param value value to set the DOC_TITLE
     */
    public void setDocTitle(String value) {
        setAttributeInternal(DOCTITLE, value);
    }

    /**
     * Gets the attribute value for DOC_NAME using the alias name DocName.
     * @return the DOC_NAME
     */
    public String getDocName() {
        return (String) getAttributeInternal(DOCNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_NAME using the alias name DocName.
     * @param value value to set the DOC_NAME
     */
    public void setDocName(String value) {
        setAttributeInternal(DOCNAME, value);
    }

    /**
     * Gets the attribute value for DID using the alias name Did1.
     * @return the DID
     */
    public Number getDid1() {
        return (Number) getAttributeInternal(DID1);
    }

    /**
     * Sets <code>value</code> as attribute value for DID using the alias name Did1.
     * @param value value to set the DID
     */
    public void setDid1(Number value) {
        setAttributeInternal(DID1, value);
    }

    /**
     * Gets the attribute value for URL using the alias name Url.
     * @return the URL
     */
    public String getUrl() {
        return (String) getAttributeInternal(URL);
    }

    /**
     * Sets <code>value</code> as attribute value for URL using the alias name Url.
     * @param value value to set the URL
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**
     * Gets the attribute value for TIPE_DOKUMEN using the alias name TipeDokumen.
     * @return the TIPE_DOKUMEN
     */
    public String getTipeDokumen() {
        return (String) getAttributeInternal(TIPEDOKUMEN);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPE_DOKUMEN using the alias name TipeDokumen.
     * @param value value to set the TIPE_DOKUMEN
     */
    public void setTipeDokumen(String value) {
        setAttributeInternal(TIPEDOKUMEN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MetaUrl.
     * @return the MetaUrl
     */
    public String getMetaUrl() {
        return (String) getAttributeInternal(METAURL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MetaUrl.
     * @param value value to set the  MetaUrl
     */
    public void setMetaUrl(String value) {
        setAttributeInternal(METAURL, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovDmsMeta1.
     */
    public RowSet getLovDmsMeta1() {
        return (RowSet)getAttributeInternal(LOVDMSMETA1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovYesNo1.
     */
    public RowSet getLovYesNo1() {
        return (RowSet)getAttributeInternal(LOVYESNO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovTipeDokumen1.
     */
    public RowSet getLovTipeDokumen1() {
        return (RowSet)getAttributeInternal(LOVTIPEDOKUMEN1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
