package app.mkp.model.view.ttf.linkdoc;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 19 02:47:54 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PreInitialDocumentViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PreInitialDocumentViewImpl() {
    }

    /**
     * Returns the variable value for pihakTerkait.
     * @return variable value for pihakTerkait
     */
    public String getpihakTerkait() {
        return (String)ensureVariableManager().getVariableValue("pihakTerkait");
    }

    /**
     * Sets <code>value</code> for variable pihakTerkait.
     * @param value value to bind as pihakTerkait
     */
    public void setpihakTerkait(String value) {
        ensureVariableManager().setVariableValue("pihakTerkait", value);
    }

    /**
     * Returns the variable value for tipeDok.
     * @return variable value for tipeDok
     */
    public String gettipeDok() {
        return (String)ensureVariableManager().getVariableValue("tipeDok");
    }

    /**
     * Sets <code>value</code> for variable tipeDok.
     * @param value value to bind as tipeDok
     */
    public void settipeDok(String value) {
        ensureVariableManager().setVariableValue("tipeDok", value);
    }

    /**
     * Returns the variable value for startDate.
     * @return variable value for startDate
     */
    public Date getstartDate() {
        return (Date)ensureVariableManager().getVariableValue("startDate");
    }

    /**
     * Sets <code>value</code> for variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(Date value) {
        ensureVariableManager().setVariableValue("startDate", value);
    }

    /**
     * Returns the variable value for endDate.
     * @return variable value for endDate
     */
    public Date getendDate() {
        return (Date)ensureVariableManager().getVariableValue("endDate");
    }

    /**
     * Sets <code>value</code> for variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(Date value) {
        ensureVariableManager().setVariableValue("endDate", value);
    }

    /**
     * Returns the variable value for idDok.
     * @return variable value for idDok
     */
    public String getidDok() {
        return (String)ensureVariableManager().getVariableValue("idDok");
    }

    /**
     * Sets <code>value</code> for variable idDok.
     * @param value value to bind as idDok
     */
    public void setidDok(String value) {
        ensureVariableManager().setVariableValue("idDok", value);
    }
}
