package app.mkp.model.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 06 12:28:56 ICT 2013
// ---------------------------------------------------------------------
public interface SecurityAM extends ApplicationModule {
    Map authenticateUser(String userLogin, String userPassword);
}
