package app.mkp.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 17 09:49:23 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelOfAuthorityAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LevelOfAuthorityAMImpl() {
    }

    /**
     * Container's getter for LoaMainView1.
     * @return LoaMainView1
     */
    public ViewObjectImpl getLoaMainView1() {
        return (ViewObjectImpl)findViewObject("LoaMainView1");
    }

    /**
     * Container's getter for LoaAuthView1.
     * @return LoaAuthView1
     */
    public ViewObjectImpl getLoaAuthView1() {
        return (ViewObjectImpl)findViewObject("LoaAuthView1");
    }

    /**
     * Container's getter for LoaMainLoaAuthViewLink1.
     * @return LoaMainLoaAuthViewLink1
     */
    public ViewLinkImpl getLoaMainLoaAuthViewLink1() {
        return (ViewLinkImpl)findViewLink("LoaMainLoaAuthViewLink1");
    }

    /**
     * Container's getter for LoaAprvrView1.
     * @return LoaAprvrView1
     */
    public ViewObjectImpl getLoaAprvrView1() {
        return (ViewObjectImpl)findViewObject("LoaAprvrView1");
    }

    /**
     * Container's getter for LoaAuthLoaAprvrViewLink1.
     * @return LoaAuthLoaAprvrViewLink1
     */
    public ViewLinkImpl getLoaAuthLoaAprvrViewLink1() {
        return (ViewLinkImpl)findViewLink("LoaAuthLoaAprvrViewLink1");
    }

    /**
     * Container's getter for LoaAprvrPtView1.
     * @return LoaAprvrPtView1
     */
    public ViewObjectImpl getLoaAprvrPtView1() {
        return (ViewObjectImpl)findViewObject("LoaAprvrPtView1");
    }

    /**
     * Container's getter for LoaAprvrLoaAprvrPtViewLink1.
     * @return LoaAprvrLoaAprvrPtViewLink1
     */
    public ViewLinkImpl getLoaAprvrLoaAprvrPtViewLink1() {
        return (ViewLinkImpl)findViewLink("LoaAprvrLoaAprvrPtViewLink1");
    }

    /**
     * Container's getter for ListPtView1.
     * @return ListPtView1
     */
    public ViewObjectImpl getListPtView1() {
        return (ViewObjectImpl)findViewObject("ListPtView1");
    }

    /**
     * Container's getter for ListVendorView1.
     * @return ListVendorView1
     */
    public ViewObjectImpl getListVendorView1() {
        return (ViewObjectImpl)findViewObject("ListVendorView1");
    }
}
