package app.mkp.model.entity.ttf.linkdoc;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 16 11:18:18 ICT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MknDokRelImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id {
            public Object get(MknDokRelImpl obj) {
                return obj.getId();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setId((DBSequence)value);
            }
        }
        ,
        IdPoOs {
            public Object get(MknDokRelImpl obj) {
                return obj.getIdPoOs();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setIdPoOs((String)value);
            }
        }
        ,
        IdKontrak {
            public Object get(MknDokRelImpl obj) {
                return obj.getIdKontrak();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setIdKontrak((String)value);
            }
        }
        ,
        IdIm {
            public Object get(MknDokRelImpl obj) {
                return obj.getIdIm();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setIdIm((String)value);
            }
        }
        ,
        Did {
            public Object get(MknDokRelImpl obj) {
                return obj.getDid();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setDid((Number)value);
            }
        }
        ,
        NoParent {
            public Object get(MknDokRelImpl obj) {
                return obj.getNoParent();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setNoParent((String)value);
            }
        }
        ,
        TipeDok {
            public Object get(MknDokRelImpl obj) {
                return obj.getTipeDok();
            }

            public void put(MknDokRelImpl obj, Object value) {
                obj.setTipeDok((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MknDokRelImpl object);

        public abstract void put(MknDokRelImpl object, Object value);

        public int index() {
            return MknDokRelImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return MknDokRelImpl.AttributesEnum.firstIndex() + MknDokRelImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = MknDokRelImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int IDPOOS = AttributesEnum.IdPoOs.index();
    public static final int IDKONTRAK = AttributesEnum.IdKontrak.index();
    public static final int IDIM = AttributesEnum.IdIm.index();
    public static final int DID = AttributesEnum.Did.index();
    public static final int NOPARENT = AttributesEnum.NoParent.index();
    public static final int TIPEDOK = AttributesEnum.TipeDok.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MknDokRelImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("app.mkp.model.entity.ttf.linkdoc.MknDokRel");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for IdPoOs, using the alias name IdPoOs.
     * @return the IdPoOs
     */
    public String getIdPoOs() {
        return (String)getAttributeInternal(IDPOOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdPoOs.
     * @param value value to set the IdPoOs
     */
    public void setIdPoOs(String value) {
        setAttributeInternal(IDPOOS, value);
    }

    /**
     * Gets the attribute value for IdKontrak, using the alias name IdKontrak.
     * @return the IdKontrak
     */
    public String getIdKontrak() {
        return (String)getAttributeInternal(IDKONTRAK);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdKontrak.
     * @param value value to set the IdKontrak
     */
    public void setIdKontrak(String value) {
        setAttributeInternal(IDKONTRAK, value);
    }

    /**
     * Gets the attribute value for IdIm, using the alias name IdIm.
     * @return the IdIm
     */
    public String getIdIm() {
        return (String)getAttributeInternal(IDIM);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdIm.
     * @param value value to set the IdIm
     */
    public void setIdIm(String value) {
        setAttributeInternal(IDIM, value);
    }

    /**
     * Gets the attribute value for Did, using the alias name Did.
     * @return the Did
     */
    public Number getDid() {
        return (Number)getAttributeInternal(DID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Did.
     * @param value value to set the Did
     */
    public void setDid(Number value) {
        setAttributeInternal(DID, value);
    }

    /**
     * Gets the attribute value for NoParent, using the alias name NoParent.
     * @return the NoParent
     */
    public String getNoParent() {
        return (String)getAttributeInternal(NOPARENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoParent.
     * @param value value to set the NoParent
     */
    public void setNoParent(String value) {
        setAttributeInternal(NOPARENT, value);
    }

    /**
     * Gets the attribute value for TipeDok, using the alias name TipeDok.
     * @return the TipeDok
     */
    public String getTipeDok() {
        return (String)getAttributeInternal(TIPEDOK);
    }

    /**
     * Sets <code>value</code> as the attribute value for TipeDok.
     * @param value value to set the TipeDok
     */
    public void setTipeDok(String value) {
        setAttributeInternal(TIPEDOK, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
             super.create(attributeList);
             SequenceImpl seq = new SequenceImpl("MKN_DOK_REL_SEQ", getDBTransaction());
             this.setId(new DBSequence(seq.getSequenceNumber()));
     }
}
